apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-sample
  labels:
    app: ui-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-sample
  template:
    metadata:
      labels:
        app: ui-sample
    spec:
      containers:
      - name: ui-sample
        image: ghcr.io/kool-dev/ui-sample:latest  # lightweight sample UI container
        ports:
        - containerPort: 80
